version: "3.4"

services:
  jaeger: 
    image: jaegertracing/all-in-one
    environment: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
      - MSSQL_PID=Developer

  create_db:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password@123" -Q "create database [Vixi]"; do sleep 5; done'
    
  run_seed:
    image: mcr.microsoft.com/mssql-tools
    restart: always
    depends_on:
      - mssql
      - create_db
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password@123" -i ./seed.sql; do sleep 5; done'    
    volumes:
      - ./seed.sql:/seed.sql

  flyway:
    image: flyway/flyway
    command: migrate
    depends_on:
      - mssql
      - create_db
    volumes:
      - ./sql:/flyway/sql
      - ./conf:/flyway/conf
